* Tasks

** TODO debounce might still be too low on the sweep, there is a bit of chatter sometimes still, 5ms more on each value?
[2026-02-10 Tue 12:40]

also in qmk we have it set up so the key positions fall through on layers, we can do that in zmk if we just change the layers that are layer locked. so we could make ({[<>]}) work in lower layer by adding lower to that i think.. worth consideration, niche but handy and i see hopefully no drawbacks to that.
[2026-02-13 Fri 15:17]

** TODO Dynamic macros
zmk doesnt have these yet (iirc, double check)
but qmk does, might as well set up the framework for it, i use them in emacs
all the time, but i could see use outside and in games for sure
simple combos to toggle them
- [ ]  Record / Stop recording combo
- [ ]  Play recorded macro
- [ ]  then im not sure if they get overwritten or if there is an amount that are stored? figure that out
- [ ]  do we need a delete macro function?
Food for thought, would come in handy sometimes, not pressing tho.
[2026-02-04 Wed 08:24]

** TODO something we could add but we would have to tweak qmk
this is a wild and weird idea and actually might be a burdern on qmk becuase the fall through on there is actually super handy, but zmk doesnt have the fall through unless we remove the layer locks on each combo

but what we could do for the lower layer is add a bunch of unique to that layer combos. might not be worth it but just thought about it
[2026-02-08 Sun 02:23]
